SELECT 
  YEAR(DIFFERENTIATION_DATE) AS YEAR, 
  (SUB_TABLE.SUB_MAX - d.SIZE_OF_COLONY) AS YEAR_DEV,
  d.ID
 FROM ECOLI_DATA d JOIN
(
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SUB_MAX
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
) SUB_TABLE
ON YEAR(d.DIFFERENTIATION_DATE) = SUB_TABLE.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC

