-- 코드를 입력하세요
SELECT ATABLE.TITLE, ATABLE.BOARD_ID AS 'BOARD_ID', REPLY_ID, BTABLE.WRITER_ID AS 'WRITER_ID', BTABLE.CONTENTS as 'CONTENTS', DATE_FORMAT(BTABLE.CREATED_DATE, '%Y-%m-%d') AS 'CREATED_DATE'
from USED_GOODS_BOARD AS ATABLE INNER JOIN USED_GOODS_REPLY AS BTABLE 
ON ATABLE.BOARD_ID = BTABLE.BOARD_ID
WHERE ATABLE.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE ASC, TITLE ASC